version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      kafka-net:
        ipv4_address: 9.9.0.10


  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://9.9.0.2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-fav-topic:2:3"
    ports:
      - "9092:9092"
    networks:
      kafka-net:
        ipv4_address: 9.9.0.2


  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://9.9.0.3:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9092"
    networks:
      kafka-net:
        ipv4_address: 9.9.0.3

  kafka3:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://9.9.0.4:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9094:9092"
    networks:
      kafka-net:
        ipv4_address: 9.9.0.4

networks:
  kafka-net:
    driver: bridge
    ipam:
     config:
       - subnet: 9.9.0.0/16  # just a random pick that works
         gateway: 9.9.0.1
