# there was an issue first, because the producer could not access kafka:9092
# thus, I followed https://stackoverflow.com/questions/55993611/why-kafka-producer-is-showing-me-error-kafka-conndns-lookup-failed-for-contain
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - '29092:29092'  # note the extra port
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://127.0.0.1:9092,OUTSIDE://localhost:9093  # i don't quite get that 127.0.0.1 thing but it works
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mytopic:1:1"  # topic name; replication factor; partition count
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
