[package]
name = "my_project_name"
version = "0.1.0"
edition = "2021"  # relevant for cargo version

[dependencies]
rand = "0.8.5"  # see: https://crates.io/crates/rand

[[bin]]
name = "main"
path = "main.rs"
